### ISSUE TITLE
EPIC: Upload animation frames for BMO app audio

### ISSUE THREAD

**Issue by NuMellow** [NuMellow/theMoFactory#38]
Create frames for phrases from the old ipad app

- [x] Talking to lorane #40 
- [x] It's BMO time #41 
- [x] Who wants to play video games #42 
- [x] I'm a dancing machine #43 
- [x] Get ready for the dance party #44 
- [x] Being too boring #45 
- [x] That's terrible #46 
- [x] That does compute #47 
- [x] That's fantastic #48 
- [x] Rather be eating pizza #49 
- [x] Congratulations #50 
- [x] BMO likes #39 
- [x] Congratulations, you are state champion #51 

Animations are [currently] in 24fps and have a canvas size of 800x480 with pixel resolution of 600

**Comment by NuMellow** [comment]
Woo Done! 🎉
